Repository Azure/azure-service-operator, pull requests merged in 2023-06, with the labels that each got.

#3036 Document upcoming 2.2.0 breaking change
  docs/hugo/content/guide/breaking-changes/_index.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.1.0.md
Labels: documentation

#3040 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-v2.1.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr

#3045 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3034 Fix secret override not applying to Status
  v2/api/machinelearningservices/v1api20210701/structure.txt
  v2/api/machinelearningservices/v1api20210701/workspaces_compute_status_arm_types_gen.go
  v2/api/machinelearningservices/v1api20210701/workspaces_compute_status_arm_types_gen_test.go
  v2/api/machinelearningservices/v1api20210701/workspaces_compute_types_gen.go
  v2/api/machinelearningservices/v1api20210701/workspaces_compute_types_gen_test.go
  v2/api/machinelearningservices/v1api20210701/zz_generated.deepcopy.go
  v2/api/machinelearningservices/v1api20210701storage/structure.txt
  v2/api/machinelearningservices/v1api20210701storage/workspaces_compute_types_gen.go
  v2/api/machinelearningservices/v1api20210701storage/workspaces_compute_types_gen_test.go
  v2/api/machinelearningservices/v1api20210701storage/zz_generated.deepcopy.go
  v2/api/machinelearningservices/v1beta20210701/structure.txt
  v2/api/machinelearningservices/v1beta20210701/workspaces_compute_status_arm_types_gen.go
  v2/api/machinelearningservices/v1beta20210701/workspaces_compute_status_arm_types_gen_test.go
  v2/api/machinelearningservices/v1beta20210701/workspaces_compute_types_gen.go
  v2/api/machinelearningservices/v1beta20210701/workspaces_compute_types_gen_test.go
  v2/api/machinelearningservices/v1beta20210701/zz_generated.deepcopy.go
  v2/api/machinelearningservices/v1beta20210701storage/structure.txt
  v2/api/machinelearningservices/v1beta20210701storage/workspaces_compute_types_gen.go
  v2/api/machinelearningservices/v1beta20210701storage/workspaces_compute_types_gen_test.go
  v2/api/machinelearningservices/v1beta20210701storage/zz_generated.deepcopy.go
  v2/api/synapse/v1api20210601/structure.txt
  v2/api/synapse/v1api20210601/workspace_status_arm_types_gen.go
  v2/api/synapse/v1api20210601/workspace_status_arm_types_gen_test.go
  v2/api/synapse/v1api20210601/workspace_types_gen.go
  v2/api/synapse/v1api20210601/workspace_types_gen_test.go
  v2/api/synapse/v1api20210601/zz_generated.deepcopy.go
  v2/api/synapse/v1api20210601storage/structure.txt
  v2/api/synapse/v1api20210601storage/workspace_types_gen.go
  v2/api/synapse/v1api20210601storage/workspace_types_gen_test.go
  v2/api/synapse/v1api20210601storage/zz_generated.deepcopy.go
  v2/tools/generator/internal/codegen/pipeline/add_secrets.go
Labels: breaking

#3041 Improve our documentation for Dev Setup
  docs/hugo/content/contributing/_index.md
  docs/hugo/content/contributing/create-a-new-release.md
  docs/hugo/content/contributing/developer-setup.md
  docs/hugo/content/contributing/images/docker-desktop-wsl.png
Labels: documentation

#3059 Fix PR Validation workflow for forks
  .github/workflows/pr-validation-fork.yml
Labels: bug 🪲

#3063 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3064 [Automated] Add API Docs
  docs/hugo/content/reference/devices/v1api20210702.md
  docs/hugo/content/reference/machinelearningservices/v1api20210701.md
  docs/hugo/content/reference/machinelearningservices/v1beta20210701.md
  docs/hugo/content/reference/synapse/v1api20210601.md
Labels: automated pr

#3075 [Automated] Add API Docs
  docs/hugo/content/reference/network/v1api20220701.md
Labels: automated pr

#3026 Mark `ManagedClusterServicePrincipalProfile.Secret` as a secret reference
  v2/api/containerservice/v1api20210501/managed_cluster_status_arm_types_gen.go
  v2/api/containerservice/v1api20210501/managed_cluster_status_arm_types_gen_test.go
  v2/api/containerservice/v1api20210501/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20210501/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20210501/structure.txt
  v2/api/containerservice/v1api20210501/zz_generated.deepcopy.go
  v2/api/containerservice/v1api20210501storage/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20210501storage/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20210501storage/structure.txt
  v2/api/containerservice/v1api20210501storage/zz_generated.deepcopy.go
  v2/api/containerservice/v1api20230201/managed_cluster_status_arm_types_gen.go
  v2/api/containerservice/v1api20230201/managed_cluster_status_arm_types_gen_test.go
  v2/api/containerservice/v1api20230201/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230201/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20230201/structure.txt
  v2/api/containerservice/v1api20230201/zz_generated.deepcopy.go
  v2/api/containerservice/v1api20230201storage/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230201storage/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20230201storage/structure.txt
  v2/api/containerservice/v1api20230201storage/zz_generated.deepcopy.go
  v2/api/containerservice/v1api20230202preview/managed_cluster_status_arm_types_gen.go
  v2/api/containerservice/v1api20230202preview/managed_cluster_status_arm_types_gen_test.go
  v2/api/containerservice/v1api20230202preview/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230202preview/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20230202preview/structure.txt
  v2/api/containerservice/v1api20230202preview/zz_generated.deepcopy.go
  v2/api/containerservice/v1api20230202previewstorage/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230202previewstorage/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1api20230202previewstorage/structure.txt
  v2/api/containerservice/v1api20230202previewstorage/zz_generated.deepcopy.go
  v2/api/containerservice/v1beta20210501/managed_cluster_status_arm_types_gen.go
  v2/api/containerservice/v1beta20210501/managed_cluster_status_arm_types_gen_test.go
  v2/api/containerservice/v1beta20210501/managed_cluster_types_gen.go
  v2/api/containerservice/v1beta20210501/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1beta20210501/structure.txt
  v2/api/containerservice/v1beta20210501/zz_generated.deepcopy.go
  v2/api/containerservice/v1beta20210501storage/managed_cluster_types_gen.go
  v2/api/containerservice/v1beta20210501storage/managed_cluster_types_gen_test.go
  v2/api/containerservice/v1beta20210501storage/structure.txt
  v2/api/containerservice/v1beta20210501storage/zz_generated.deepcopy.go
  v2/azure-arm.yaml
  v2/internal/controllers/controller_resources_gen.go
Labels: breaking

#3083 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3084 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/search/_index.md
  docs/hugo/content/reference/search/v1api20220901.md
  docs/v2/azure/supported-resources/search.md
Labels: automated pr

#3100 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3101 [Automated] Add API Docs
  docs/hugo/content/reference/containerservice/v1api20210501.md
  docs/hugo/content/reference/containerservice/v1api20230201.md
  docs/hugo/content/reference/containerservice/v1api20230202preview.md
  docs/hugo/content/reference/containerservice/v1beta20210501.md
Labels: automated pr
