Repository Azure/azure-service-operator, pull requests merged in 2023-10, with the labels that each got.

#3352 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3353 [Automated] Add API Docs
  docs/hugo/content/reference/containerservice/v1api20230315preview.md
Labels: automated pr

#3349 Clarify MySQL AAD requirements
  v2/samples/dbformysql/v1api/v1_user_aad.yaml
Labels: documentation

#3384 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/apimanagement/_index.md
  docs/hugo/content/reference/apimanagement/v1api20220801.md
  docs/hugo/content/reference/network/_index.md
  docs/hugo/content/reference/network/v1api20220401.md
Labels: automated pr

#3383 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3405 Add documentation about TypeTransformers
  v2/azure-arm.yaml
Labels: documentation

#3417 Allow Spec types to be initialized from multiple Status types
  v2/tools/generator/internal/codegen/pipeline/inject_spec_initialization_functions.go
  v2/tools/generator/internal/codegen/pipeline/inject_spec_initialization_functions_test.go
  v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectSpecInitializationFunctions/person-v20200101.golden
  v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectSpecInitializationFunctions/person-v20200101storage.golden
Labels: bug 🪲

#3421 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/apimanagement/v1api20220801.md
  docs/hugo/content/reference/insights/_index.md
  docs/hugo/content/reference/insights/v1api20180301.md
  docs/hugo/content/reference/insights/v1api20220615.md
  docs/hugo/content/reference/insights/v1api20221001.md
  docs/hugo/content/reference/insights/v1api20230101.md
  docs/hugo/content/reference/keyvault/v1api20210401preview.md
  docs/hugo/content/reference/keyvault/v1beta20210401preview.md
Labels: automated pr

#3420 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3400 KeyVault Documentation
  docs/hugo/content/guide/_index.md
  docs/hugo/content/guide/keyvaults/_index.md
Labels: documentation

#3462 Update dependencies
  v2/cmd/asoctl/go.mod
  v2/cmd/asoctl/go.sum
  v2/go.mod
  v2/go.sum
  v2/internal/controllers/recordings/Test_ReconcilePolicySkip_CreatesSecretAndConfigMap.yaml
  v2/internal/controllers/recordings/Test_SQL_Server_CRUD.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Eventgrid_v1beta_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Machinelearningservices_v1api_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Machinelearningservices_v1beta_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sql_v1api_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Storage_v1beta_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Storage_StorageAccount_20210401_SecretsFromAzure.yaml
  v2/internal/controllers/recordings/Test_Storage_StorageAccount_SecretsFromAzure.yaml
  v2/internal/controllers/recordings/Test_TwoObjectsWriteSameSecret_WarningConditionIsSetOnSecond.yaml
  v2/internal/controllers/recordings/Test_WhenObjectDeleted_SecretIsDeleted.yaml
  v2/internal/controllers/recordings/Test_WhenObjectPullSecretsAndSecretAlreadyExists_WarningConditionIsSet.yaml
  v2/tools/generator/go.mod
  v2/tools/generator/go.sum
Labels: dependencies

#3452 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
Labels: automated pr

#3472 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3473 [Automated] Add API Docs
  docs/hugo/content/reference/apimanagement/v1api20220801.md
  docs/hugo/content/reference/network/v1api20220701.md
Labels: automated pr

#3422 Update documentation around CRD removal
  docs/hugo/content/guide/uninstalling.md
Labels: documentation
