Repository Azure/azure-service-operator, pull requests merged in 2023-04, with the labels that each got.

#2833 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#2812 Design document for Post Reconciliation Extension
  docs/hugo/content/design/ADR-2023-03-Post-Reconciliation-Extension.md
Labels: P0

#2852 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#2067 Adoption design
  docs/hugo/content/design/ADR-2023-02-Adoption-Policy.md
Labels: P0

#2879 Fix missing log messages
  v2/tools/asoctl/cmd/clean-crds.go
  v2/tools/asoctl/cmd/import_azure_resource.go
  v2/tools/asoctl/cmd/log.go
  v2/tools/asoctl/cmd/root.go
  v2/tools/asoctl/internal/crd/cleaner.go
Labels: bug

#2885 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-v2.0.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr

#2886 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#2917 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#2919 ARMClientCache should only check the namespace the resource is in
  v2/internal/reconcilers/arm/arm_client_cache.go
  v2/internal/reconcilers/arm/arm_client_cache_test.go
Labels: breaking
