Repository Azure/azure-service-operator, pull requests merged in 2023-11, with the labels that each got.

#3499 Relocate appconfiguration Storage
  v2/api/appconfiguration/customizations/configuration_store_extension_types_gen.go
  v2/api/appconfiguration/customizations/configuration_store_extensions.go
  v2/api/appconfiguration/v1api20220501/configuration_store_types_gen.go
  v2/api/appconfiguration/v1api20220501/configuration_store_types_gen_test.go
  v2/api/appconfiguration/v1api20220501/storage/configuration_store_types_gen.go
  v2/api/appconfiguration/v1api20220501/storage/configuration_store_types_gen_test.go
  v2/api/appconfiguration/v1api20220501/storage/groupversion_info_gen.go
  v2/api/appconfiguration/v1api20220501/storage/structure.txt
  v2/api/appconfiguration/v1api20220501/storage/zz_generated.deepcopy.go
  v2/api/appconfiguration/v1beta20220501/configuration_store_types_gen.go
  v2/api/appconfiguration/v1beta20220501/configuration_store_types_gen_test.go
  v2/api/appconfiguration/v1beta20220501/storage/configuration_store_types_gen.go
  v2/api/appconfiguration/v1beta20220501/storage/configuration_store_types_gen_test.go
  v2/api/appconfiguration/v1beta20220501/storage/groupversion_info_gen.go
  v2/api/appconfiguration/v1beta20220501/storage/structure.txt
  v2/api/appconfiguration/v1beta20220501/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3500 Relocate resouces Storage
  v2/api/keyvault/customizations/vault_extensions.go
  v2/api/resources/customizations/resource_group_extension_types_gen.go
  v2/api/resources/v1api20200601/resource_group_types_gen.go
  v2/api/resources/v1api20200601/resource_group_types_gen_test.go
  v2/api/resources/v1api20200601/storage/groupversion_info_gen.go
  v2/api/resources/v1api20200601/storage/resource_group_types_gen.go
  v2/api/resources/v1api20200601/storage/resource_group_types_gen_test.go
  v2/api/resources/v1api20200601/storage/structure.txt
  v2/api/resources/v1api20200601/storage/zz_generated.deepcopy.go
  v2/api/resources/v1beta20200601/resource_group_types_gen.go
  v2/api/resources/v1beta20200601/resource_group_types_gen_test.go
  v2/api/resources/v1beta20200601/storage/groupversion_info_gen.go
  v2/api/resources/v1beta20200601/storage/resource_group_types_gen.go
  v2/api/resources/v1beta20200601/storage/resource_group_types_gen_test.go
  v2/api/resources/v1beta20200601/storage/structure.txt
  v2/api/resources/v1beta20200601/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3498 [Automated] Add API Docs
  docs/hugo/content/reference/insights/v1api20221001.md
Labels: automated pr

#3497 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
Labels: automated pr

#3502 Relocate subscription storage
  v2/api/subscription/customizations/alias_extension_types_gen.go
  v2/api/subscription/customizations/alias_extensions.go
  v2/api/subscription/v1api20211001/alias_types_gen.go
  v2/api/subscription/v1api20211001/alias_types_gen_test.go
  v2/api/subscription/v1api20211001/storage/alias_types_gen.go
  v2/api/subscription/v1api20211001/storage/alias_types_gen_test.go
  v2/api/subscription/v1api20211001/storage/groupversion_info_gen.go
  v2/api/subscription/v1api20211001/storage/structure.txt
  v2/api/subscription/v1api20211001/storage/zz_generated.deepcopy.go
  v2/api/subscription/v1beta20211001/alias_types_gen.go
  v2/api/subscription/v1beta20211001/alias_types_gen_test.go
  v2/api/subscription/v1beta20211001/storage/alias_types_gen.go
  v2/api/subscription/v1beta20211001/storage/alias_types_gen_test.go
  v2/api/subscription/v1beta20211001/storage/groupversion_info_gen.go
  v2/api/subscription/v1beta20211001/storage/structure.txt
  v2/api/subscription/v1beta20211001/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3521 Relocate datafactory storage
  v2/api/datafactory/customizations/factory_extension_types_gen.go
  v2/api/datafactory/v1api20180601/factory_types_gen.go
  v2/api/datafactory/v1api20180601/factory_types_gen_test.go
  v2/api/datafactory/v1api20180601/storage/factory_types_gen.go
  v2/api/datafactory/v1api20180601/storage/factory_types_gen_test.go
  v2/api/datafactory/v1api20180601/storage/groupversion_info_gen.go
  v2/api/datafactory/v1api20180601/storage/structure.txt
  v2/api/datafactory/v1api20180601/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3523 Relocate eventhub storage
  v2/api/eventhub/customizations/namespace_extension_types_gen.go
  v2/api/eventhub/customizations/namespaces_authorization_rule_extension_types_gen.go
  v2/api/eventhub/customizations/namespaces_eventhub_extension_types_gen.go
  v2/api/eventhub/customizations/namespaces_eventhubs_authorization_rule_extension_types_gen.go
  v2/api/eventhub/customizations/namespaces_eventhubs_consumer_group_extension_types_gen.go
  v2/api/eventhub/v1api20211101/namespace_types_gen.go
  v2/api/eventhub/v1api20211101/namespace_types_gen_test.go
  v2/api/eventhub/v1api20211101/namespaces_authorization_rule_types_gen.go
  v2/api/eventhub/v1api20211101/namespaces_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1api20211101/namespaces_eventhub_types_gen.go
  v2/api/eventhub/v1api20211101/namespaces_eventhub_types_gen_test.go
  v2/api/eventhub/v1api20211101/namespaces_eventhubs_authorization_rule_types_gen.go
  v2/api/eventhub/v1api20211101/namespaces_eventhubs_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1api20211101/namespaces_eventhubs_consumer_group_types_gen.go
  v2/api/eventhub/v1api20211101/namespaces_eventhubs_consumer_group_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/groupversion_info_gen.go
  v2/api/eventhub/v1api20211101/storage/namespace_types_gen.go
  v2/api/eventhub/v1api20211101/storage/namespace_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/namespaces_authorization_rule_types_gen.go
  v2/api/eventhub/v1api20211101/storage/namespaces_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhub_types_gen.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhub_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhubs_authorization_rule_types_gen.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhubs_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhubs_consumer_group_types_gen.go
  v2/api/eventhub/v1api20211101/storage/namespaces_eventhubs_consumer_group_types_gen_test.go
  v2/api/eventhub/v1api20211101/storage/structure.txt
  v2/api/eventhub/v1api20211101/storage/zz_generated.deepcopy.go
  v2/api/eventhub/v1beta20211101/namespace_types_gen.go
  v2/api/eventhub/v1beta20211101/namespace_types_gen_test.go
  v2/api/eventhub/v1beta20211101/namespaces_authorization_rule_types_gen.go
  v2/api/eventhub/v1beta20211101/namespaces_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhub_types_gen.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhub_types_gen_test.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhubs_authorization_rule_types_gen.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhubs_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhubs_consumer_group_types_gen.go
  v2/api/eventhub/v1beta20211101/namespaces_eventhubs_consumer_group_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/groupversion_info_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespace_types_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespace_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_authorization_rule_types_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhub_types_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhub_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhubs_authorization_rule_types_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhubs_authorization_rule_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhubs_consumer_group_types_gen.go
  v2/api/eventhub/v1beta20211101/storage/namespaces_eventhubs_consumer_group_types_gen_test.go
  v2/api/eventhub/v1beta20211101/storage/structure.txt
  v2/api/eventhub/v1beta20211101/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3524 Relocate web storage
  v2/api/web/customizations/server_farm_extension_types_gen.go
  v2/api/web/customizations/site_extension_types_gen.go
  v2/api/web/v1api20220301/server_farm_types_gen.go
  v2/api/web/v1api20220301/server_farm_types_gen_test.go
  v2/api/web/v1api20220301/site_types_gen.go
  v2/api/web/v1api20220301/site_types_gen_test.go
  v2/api/web/v1api20220301/storage/groupversion_info_gen.go
  v2/api/web/v1api20220301/storage/server_farm_types_gen.go
  v2/api/web/v1api20220301/storage/server_farm_types_gen_test.go
  v2/api/web/v1api20220301/storage/site_types_gen.go
  v2/api/web/v1api20220301/storage/site_types_gen_test.go
  v2/api/web/v1api20220301/storage/structure.txt
  v2/api/web/v1api20220301/storage/zz_generated.deepcopy.go
  v2/api/web/v1beta20220301/server_farm_types_gen.go
  v2/api/web/v1beta20220301/server_farm_types_gen_test.go
  v2/api/web/v1beta20220301/site_types_gen.go
  v2/api/web/v1beta20220301/site_types_gen_test.go
  v2/api/web/v1beta20220301/storage/groupversion_info_gen.go
  v2/api/web/v1beta20220301/storage/server_farm_types_gen.go
  v2/api/web/v1beta20220301/storage/server_farm_types_gen_test.go
  v2/api/web/v1beta20220301/storage/site_types_gen.go
  v2/api/web/v1beta20220301/storage/site_types_gen_test.go
  v2/api/web/v1beta20220301/storage/structure.txt
  v2/api/web/v1beta20220301/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3520 Relocate batch storage
  v2/api/batch/customizations/batch_account_extension_types_gen.go
  v2/api/batch/v1api20210101/batch_account_types_gen.go
  v2/api/batch/v1api20210101/batch_account_types_gen_test.go
  v2/api/batch/v1api20210101/storage/batch_account_types_gen.go
  v2/api/batch/v1api20210101/storage/batch_account_types_gen_test.go
  v2/api/batch/v1api20210101/storage/groupversion_info_gen.go
  v2/api/batch/v1api20210101/storage/structure.txt
  v2/api/batch/v1api20210101/storage/zz_generated.deepcopy.go
  v2/api/batch/v1beta20210101/batch_account_types_gen.go
  v2/api/batch/v1beta20210101/batch_account_types_gen_test.go
  v2/api/batch/v1beta20210101/storage/batch_account_types_gen.go
  v2/api/batch/v1beta20210101/storage/batch_account_types_gen_test.go
  v2/api/batch/v1beta20210101/storage/groupversion_info_gen.go
  v2/api/batch/v1beta20210101/storage/structure.txt
  v2/api/batch/v1beta20210101/storage/zz_generated.deepcopy.go
  v2/internal/controllers/controller_resources_gen.go
  v2/tools/generator/internal/astmodel/storage_package_reference.go
Labels: technical-debt 📈

#3540 Add support for explicitEmptyCollections payloadType
  docs/hugo/content/design/ADR-2023-04-Patch-Collections.md
  scripts/v2/create-kind-wi-storage.sh
  v2/api/containerservice/customizations/fleet_extensions.go
  v2/api/containerservice/v1api20210501/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20210501/managed_clusters_agent_pool_types_gen.go
  v2/api/containerservice/v1api20230201/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230201/managed_clusters_agent_pool_types_gen.go
  v2/api/containerservice/v1api20230202preview/managed_cluster_types_gen.go
  v2/api/containerservice/v1api20230202preview/managed_clusters_agent_pool_types_gen.go
  v2/api/containerservice/v1api20230315preview/fleet_types_gen.go
  v2/api/containerservice/v1beta20210501/managed_cluster_types_gen.go
  v2/api/containerservice/v1beta20210501/managed_clusters_agent_pool_types_gen.go
  v2/azure-arm.yaml
  v2/internal/controllers/crd_aks_fleet_20230315preview_test.go
  v2/internal/controllers/crd_aks_managedcluster_20230102preview_test.go
  v2/internal/controllers/crd_keyvault_test.go
  v2/internal/controllers/crd_machinelearningservices_test.go
  v2/internal/controllers/latest_reconciled_generation_test.go
  v2/internal/controllers/recordings/Test_AKS_Fleet_20230315_CRUD.yaml
  v2/internal/controllers/recordings/Test_AKS_ManagedCluster_20210501_CRUD.yaml
  v2/internal/controllers/recordings/Test_AKS_ManagedCluster_20230202Preview_CRUD.yaml
  v2/internal/controllers/recordings/Test_KeyVault_Vault_CRUD.yaml
  v2/internal/controllers/recordings/Test_KeyVault_Vault_FromConfig_CRUD.yaml
  v2/internal/controllers/recordings/Test_Latest_Reconciled_Generation_Reconciles_AllEvents.yaml
  v2/internal/controllers/recordings/Test_MachineLearning_Workspaces_CRUD.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1api20210501_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1api20230201_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1api20230202preview_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1api20230315preview_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1beta20210501_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1beta20230201_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Containerservice_v1beta20230202preview_CreationAndDeletion.yaml
  v2/tools/generator/internal/armconversion/arm_conversion_function.go
  v2/tools/generator/internal/armconversion/convert_from_arm_function_builder.go
  v2/tools/generator/internal/armconversion/convert_to_arm_function_builder.go
  v2/tools/generator/internal/armconversion/shared.go
  v2/tools/generator/internal/astmodel/conversion_function_builder.go
  v2/tools/generator/internal/codegen/code_generator.go
  v2/tools/generator/internal/codegen/pipeline/add_arm_conversion_interface.go
  v2/tools/generator/internal/codegen/pipeline/create_arm_types.go
  v2/tools/generator/internal/codegen/pipeline/create_arm_types_test.go
  v2/tools/generator/internal/config/group_configuration.go
Labels: capz

#3543 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/authorization/_index.md
  docs/hugo/content/reference/authorization/v1api20220401.md
  docs/hugo/content/reference/cache/v1api20230401.md
  docs/hugo/content/reference/containerservice/v1api20230315preview.md
  docs/hugo/content/reference/synapse/v1api20210601.md
Labels: automated pr

#3542 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3550 Add v2.4.0 breaking change documentation
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.2.0.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.4.0.md
Labels: documentation

#3496 Document Dependencies
  .devcontainer/install-dependencies.sh
  Taskfile.yml
  docs/hugo/content/contributing/dependencies.md
  docs/v2/dependencies-footer.md
  docs/v2/dependencies-header.md
Labels: documentation

#3554 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-2.4.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr

#3568 Update documentation for the v2.4.0 release
  docs/hugo/content/guide/breaking-changes/_index.md
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/apimanagement/_index.md
  docs/hugo/content/reference/authorization/_index.md
  docs/hugo/content/reference/containerservice/_index.md
  docs/hugo/content/reference/insights/_index.md
  docs/hugo/content/reference/kubernetesconfiguration/_index.md
  docs/hugo/content/reference/network/_index.md
  hack/crossplane/azure-crossplane.yaml
  v2/azure-arm.yaml
Labels: documentation

#3530 Controller should use HEAD if GET is not available
  v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
  v2/pkg/genruntime/base_types.go
  v2/pkg/genruntime/kubernetes_resource.go
Labels: microsoft.apimanagement

#3577 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3578 [Automated] Add API Docs
  docs/hugo/content/guide/configmaps.md
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/appconfiguration/v1beta20220501.md
  docs/hugo/content/reference/authorization/v1beta20200801preview.md
  docs/hugo/content/reference/batch/v1beta20210101.md
  docs/hugo/content/reference/cache/v1beta20201201.md
  docs/hugo/content/reference/cache/v1beta20210301.md
  docs/hugo/content/reference/cdn/v1beta20210601.md
  docs/hugo/content/reference/compute/v1beta20200930.md
  docs/hugo/content/reference/compute/v1beta20201201.md
  docs/hugo/content/reference/compute/v1beta20210701.md
  docs/hugo/content/reference/compute/v1beta20220301.md
  docs/hugo/content/reference/containerinstance/v1beta20211001.md
  docs/hugo/content/reference/containerregistry/v1beta20210901.md
  docs/hugo/content/reference/containerservice/v1beta20210501.md
  docs/hugo/content/reference/dbformariadb/v1beta20180601.md
  docs/hugo/content/reference/dbformysql/v1beta1.md
  docs/hugo/content/reference/dbformysql/v1beta20210501.md
  docs/hugo/content/reference/dbforpostgresql/v1beta20210601.md
  docs/hugo/content/reference/dbforpostgresql/v1beta20220120preview.md
  docs/hugo/content/reference/documentdb/v1beta20210515.md
  docs/hugo/content/reference/eventgrid/v1beta20200601.md
  docs/hugo/content/reference/eventhub/v1beta20211101.md
  docs/hugo/content/reference/insights/v1beta20180501preview.md
  docs/hugo/content/reference/insights/v1beta20200202.md
  docs/hugo/content/reference/keyvault/v1beta20210401preview.md
  docs/hugo/content/reference/kubernetesconfiguration/_index.md
  docs/hugo/content/reference/kubernetesconfiguration/v1api20230501.md
  docs/hugo/content/reference/machinelearningservices/v1beta20210701.md
  docs/hugo/content/reference/managedidentity/v1beta20181130.md
  docs/hugo/content/reference/managedidentity/v1beta20220131preview.md
  docs/hugo/content/reference/network/v1beta20180901.md
  docs/hugo/content/reference/network/v1beta20201101.md
  docs/hugo/content/reference/operationalinsights/v1beta20210601.md
  docs/hugo/content/reference/resources/v1beta20200601.md
  docs/hugo/content/reference/servicebus/v1beta20210101preview.md
  docs/hugo/content/reference/signalrservice/v1beta20211001.md
  docs/hugo/content/reference/storage/v1beta20210401.md
  docs/hugo/content/reference/subscription/v1beta20211001.md
  docs/hugo/content/reference/web/v1beta20220301.md
Labels: automated pr

#3556 Allow AsDeclarations to return an error
  v2/tools/generator/internal/astmodel/allof_type.go
  v2/tools/generator/internal/astmodel/allof_type_test.go
  v2/tools/generator/internal/astmodel/array_type.go
  v2/tools/generator/internal/astmodel/enum_type.go
  v2/tools/generator/internal/astmodel/errored_type.go
  v2/tools/generator/internal/astmodel/external_type_name.go
  v2/tools/generator/internal/astmodel/file_definition.go
  v2/tools/generator/internal/astmodel/flagged_type.go
  v2/tools/generator/internal/astmodel/interface_type.go
  v2/tools/generator/internal/astmodel/internal_type_name.go
  v2/tools/generator/internal/astmodel/map_type.go
  v2/tools/generator/internal/astmodel/object_type.go
  v2/tools/generator/internal/astmodel/oneof_type.go
  v2/tools/generator/internal/astmodel/oneof_type_test.go
  v2/tools/generator/internal/astmodel/optional_type.go
  v2/tools/generator/internal/astmodel/primitive_type.go
  v2/tools/generator/internal/astmodel/resource_type.go
  v2/tools/generator/internal/astmodel/type.go
  v2/tools/generator/internal/astmodel/type_definition.go
  v2/tools/generator/internal/astmodel/type_definition_test.go
  v2/tools/generator/internal/astmodel/validated_type.go
  v2/tools/generator/internal/conversions/property_bag_member_type.go
Labels: technical-debt 📈

#3492 Allow Function Handlers to return errors
  v2/tools/generator/internal/armconversion/arm_spec_interface.go
  v2/tools/generator/internal/astmodel/std_references.go
  v2/tools/generator/internal/codegen/pipeline/apply_defaulter_and_validator_interfaces.go
  v2/tools/generator/internal/codegen/pipeline/inject_property_assignment_functions.go
  v2/tools/generator/internal/functions/common.go
  v2/tools/generator/internal/functions/conditions_functions.go
  v2/tools/generator/internal/functions/empty_status_function.go
  v2/tools/generator/internal/functions/get_resource_type_function.go
  v2/tools/generator/internal/functions/get_spec_function.go
  v2/tools/generator/internal/functions/get_status_function.go
  v2/tools/generator/internal/functions/hub_function.go
  v2/tools/generator/internal/functions/initialize_spec_function.go
  v2/tools/generator/internal/functions/kubernetes_admissions_defaulter.go
  v2/tools/generator/internal/functions/kubernetes_admissions_defaults.go
  v2/tools/generator/internal/functions/kubernetes_admissions_validations.go
  v2/tools/generator/internal/functions/kubernetes_admissions_validator.go
  v2/tools/generator/internal/functions/kubernetes_exporter_function.go
  v2/tools/generator/internal/functions/locatable_resource_function.go
  v2/tools/generator/internal/functions/new_empty_arm_value_function.go
  v2/tools/generator/internal/functions/object_function.go
  v2/tools/generator/internal/functions/resource_function.go
  v2/tools/generator/internal/interfaces/kubernetes_resource_interface.go
Labels: technical-debt 📈

#3594 Adds a proper index page to our design docs
  docs/hugo/content/design/_index.md
Labels: documentation

#3598 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr
