Repository Azure/azure-service-operator, pull requests merged in 2024-08, with the labels that each got.

#4143 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4177 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/apimanagement/v1api20230501preview.md
  docs/hugo/content/reference/compute/_index.md
  docs/hugo/content/reference/compute/v1api20240302.md
  docs/hugo/content/reference/containerservice/v1api20210501.md
  docs/hugo/content/reference/containerservice/v1api20230201.md
  docs/hugo/content/reference/containerservice/v1api20230202preview.md
  docs/hugo/content/reference/containerservice/v1api20231001.md
  docs/hugo/content/reference/containerservice/v1api20231102preview.md
  docs/hugo/content/reference/containerservice/v1api20240402preview.md
  docs/hugo/content/reference/documentdb/v1api20231115.md
Labels: automated pr

#4176 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4185 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4186 [Automated] Add API Docs
  docs/hugo/content/reference/containerservice/v1api20230202preview.md
Labels: automated pr

#4190 Add contact details to our documentation site
  docs/hugo/content/_index.md
  docs/hugo/content/guide/_index.md
Labels: documentation

#4192 Fix the type of DelegatedManagedIdentityResourceId
  v2/api/authorization/v1api20200801preview/role_assignment_spec_arm_types_gen.go
  v2/api/authorization/v1api20200801preview/role_assignment_types_gen.go
  v2/api/authorization/v1api20200801preview/role_assignment_types_gen_test.go
  v2/api/authorization/v1api20200801preview/storage/role_assignment_types_gen.go
  v2/api/authorization/v1api20200801preview/storage/role_assignment_types_gen_test.go
  v2/api/authorization/v1api20200801preview/storage/structure.txt
  v2/api/authorization/v1api20200801preview/storage/zz_generated.deepcopy.go
  v2/api/authorization/v1api20200801preview/structure.txt
  v2/api/authorization/v1api20200801preview/zz_generated.deepcopy.go
  v2/api/authorization/v1api20220401/role_assignment_spec_arm_types_gen.go
  v2/api/authorization/v1api20220401/role_assignment_types_gen.go
  v2/api/authorization/v1api20220401/role_assignment_types_gen_test.go
  v2/api/authorization/v1api20220401/storage/role_assignment_types_gen.go
  v2/api/authorization/v1api20220401/storage/role_assignment_types_gen_test.go
  v2/api/authorization/v1api20220401/storage/structure.txt
  v2/api/authorization/v1api20220401/storage/zz_generated.deepcopy.go
  v2/api/authorization/v1api20220401/structure.txt
  v2/api/authorization/v1api20220401/zz_generated.deepcopy.go
  v2/azure-arm.yaml
Labels: breaking

#4195 [Automated] Add API Docs
  docs/hugo/content/reference/authorization/v1api20200801preview.md
  docs/hugo/content/reference/authorization/v1api20220401.md
  docs/hugo/content/reference/containerservice/v1api20231102preview.md
  docs/hugo/content/reference/containerservice/v1api20240402preview.md
Labels: automated pr

#4194 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4202 Improve documentation
  docs/hugo/content/_index.md
  docs/hugo/content/guide/best-practices/_index.md
  docs/hugo/content/guide/diagnosing-problems.md
  docs/hugo/content/guide/frequently-asked-questions.md
  v2/charts/azure-service-operator/values.yaml
Labels: documentation

#4209 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-2.9.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
  v2/charts/azure-service-operator/templates/v1_service_azureserviceoperator-controller-manager-metrics-service.yaml
  v2/charts/azure-service-operator/templates/v1_service_azureserviceoperator-webhook-service.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr

#4230 Add missing SQL User to documentation index
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/network.frontdoor/_index.md
  docs/hugo/content/reference/sql/_index.md
  v2/azure-arm.yaml
Labels: documentation
