Repository Azure/azure-service-operator, pull requests merged in 2024-04, with the labels that each got.

#3899 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3903 Update docs for v2.6.0 release
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/apimanagement/_index.md
  docs/hugo/content/reference/cdn/_index.md
  docs/hugo/content/reference/compute/_index.md
  docs/hugo/content/reference/containerservice/_index.md
  docs/hugo/content/reference/dbforpostgresql/_index.md
  docs/hugo/content/reference/network.frontdoor/_index.md
  v2/azure-arm.yaml
Labels: documentation

#3891 Improve signature of TestCase.AsFuncs
  v2/tools/generator/internal/astmodel/test_case.go
  v2/tools/generator/internal/astmodel/test_case_test.go
  v2/tools/generator/internal/astmodel/test_file_definition.go
  v2/tools/generator/internal/testcases/json_serialization_test_case.go
  v2/tools/generator/internal/testcases/property_assignment_test_case.go
  v2/tools/generator/internal/testcases/resource_conversion_test_case.go
Labels: technical-debt 📈

#3904 Fix v3 recording infrastructure
  v2/internal/testcommon/creds/creds.go
  v2/internal/testcommon/kube_per_test_context.go
  v2/internal/testcommon/vcr/redact.go
  v2/internal/testcommon/vcr/v1/error_translating_roundtripper.go
  v2/internal/testcommon/vcr/v1/test_replayer.go
  v2/internal/testcommon/vcr/v3/error_translating_roundtripper.go
  v2/internal/testcommon/vcr/v3/replay_roundtripper.go
  v2/internal/testcommon/vcr/v3/replay_roundtripper_test.go
  v2/internal/testcommon/vcr/v3/test_recorder.go
  v2/internal/testcommon/vcr/v3/tracking_roundtripper.go
Labels: test

#3898 Add ASOv1 to ASOv2 migration guide
  Taskfile.yml
  docs/hugo/content/_index.md
  docs/hugo/content/guide/asov1-asov2-migration/_index.md
  docs/hugo/content/guide/asov1-asov2-migration/azuresql.md
  docs/hugo/content/guide/asov1-asov2-migration/databaseusers.md
  docs/hugo/content/guide/asov1-asov2-migration/eventhub.md
  docs/hugo/content/guide/asov1-asov2-migration/mysql.md
  docs/hugo/content/guide/asov1-asov2-migration/postgresql.md
  docs/hugo/content/guide/asov1-asov2-migration/redis.md
  docs/hugo/content/guide/asov1-asov2-migration/storage.md
  docs/hugo/content/guide/asov1-asov2-migration/storagecontainer.md
  docs/hugo/content/guide/uninstalling.md
  docs/hugo/content/tools/asoctl.md
  docs/operator-bundle/testing-and-releasing.md
  v2/README.md
Labels: documentation

#3909 Improve docs
  docs/hugo/content/contributing/_index.md
  docs/hugo/content/contributing/add-a-new-code-generated-resource.md
  docs/hugo/content/contributing/running-a-development-version.md
  docs/hugo/content/contributing/testing.md
  docs/hugo/content/guide/diagnosing-problems.md
Labels: documentation

#3913 [Automated] Add API Docs
  docs/hugo/content/reference/containerservice/v1api20230315preview.md
  docs/hugo/content/reference/eventhub/v1api20211101.md
Labels: automated pr

#3912 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3928 Fix broken docs links
  docs/hugo/content/guide/asov1-asov2-migration/databaseusers.md
  docs/hugo/content/guide/secrets.md
Labels: documentation

#3925 Fix bug where we could fail to emit user requested secrets or configmaps
  v2/internal/controllers/edge_case_test.go
  v2/internal/controllers/recordings/Test_CreateCosmosAccountWithSkipReconcile_SecretsAreWritten.yaml
  v2/pkg/genruntime/configmaps/collector.go
  v2/pkg/genruntime/configmaps/collector_test.go
  v2/pkg/genruntime/secrets/collector.go
  v2/pkg/genruntime/secrets/collector_test.go
  v2/samples/machinelearningservices/v1api/v1api20210701_workspace.yaml
Labels: bug 🪲, breaking

#3940 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/dbformysql/_index.md
  docs/hugo/content/reference/dbformysql/v1api20210501.md
  docs/hugo/content/reference/dbformysql/v1api20230630.md
Labels: automated pr

#3939 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3926 Refactor to combine samples and refs in samples testing suite
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Apimanagement_v1api20220801_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Apimanagement_v1api20230501preview_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Authorization_v1api20200801preview_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Authorization_v1api20220401_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sql_v1api20211101_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sql_v1api_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sqldatabase_v1api_CreationAndDeletion.yaml
  v2/internal/controllers/samples_test.go
  v2/samples/sql/v1api20211101/refs/v1api20210401_storageaccount.yaml
  v2/samples/sql/v1api20211101/refs/v1api20210401_storageaccountsblobservice.yaml
  v2/samples/sql/v1api20211101/v1api20211101_serversauditingsetting.yaml
  v2/samples/sql/v1api20211101/v1api20211101_serversdatabasesauditingsetting.yaml
  v2/samples/sql/v1api20211101/v1api20211101_serversdatabasesvulnerabilityassessment.yaml
  v2/samples/sql/v1api20211101/v1api20211101_serversvulnerabilityassessment.yaml
Labels: test, technical-debt 📈

#3950 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3951 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/containerservice/v1api20230201.md
  docs/hugo/content/reference/containerservice/v1api20230202preview.md
  docs/hugo/content/reference/containerservice/v1api20231001.md
  docs/hugo/content/reference/dataprotection/_index.md
  docs/hugo/content/reference/dataprotection/v1api20230101.md
  docs/hugo/content/reference/dataprotection/v1api20231101.md
  docs/hugo/content/reference/insights/v1api20220615.md
  docs/hugo/content/reference/kubernetesconfiguration/v1api20230501.md
  docs/hugo/content/reference/managedidentity/v1api20230131.md
Labels: automated pr

#3966 Improve ownership, adoption, and FAQ documentation
  .github/workflows/create-release-experimental.yml
  docs/hugo/content/guide/adoption.md
  docs/hugo/content/guide/annotations.md
  docs/hugo/content/guide/aso-controller-settings-options.md
  docs/hugo/content/guide/authentication/_index.md
  docs/hugo/content/guide/best-practices/_index.md
  docs/hugo/content/guide/breaking-changes/_index.md
  docs/hugo/content/guide/conditions.md
  docs/hugo/content/guide/configmaps.md
  docs/hugo/content/guide/diagnosing-problems.md
  docs/hugo/content/guide/frequently-asked-questions.md
  docs/hugo/content/guide/keyvaults.md
  docs/hugo/content/guide/metrics.md
  docs/hugo/content/guide/ownership.md
  docs/hugo/content/guide/secrets.md
Labels: documentation

#3970 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-2.7.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr

#3973 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr
