Repository Azure/azure-service-operator, pull requests merged in 2024-03, with the labels that each got.

#3840 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3850 Avoid phrasing that looks like an annotation
  docs/hugo/content/design/ADR-2022-11-Resource-Import.md
Labels: documentation

#3853 Fix asoctl import bug
  v2/cmd/asoctl/internal/importing/importable_arm_resource.go
  v2/cmd/asoctl/internal/importing/resource_import_result.go
  v2/cmd/asoctl/internal/importing/resource_importer.go
Labels: bug 🪲

#3862 Fix panic in asoctl
  v2/cmd/asoctl/internal/importing/find_group_kind.go
  v2/cmd/asoctl/internal/importing/importable_arm_resource.go
  v2/cmd/asoctl/internal/importing/importable_arm_resource_test.go
Labels: bug 🪲

#3851 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#3881 Eliminate panic in InterfaceImplementer AsDeclarations()
  v2/tools/generator/internal/astbuilder/builder.go
  v2/tools/generator/internal/astbuilder/declarations.go
  v2/tools/generator/internal/astbuilder/statements.go
  v2/tools/generator/internal/astmodel/interface_implementer.go
  v2/tools/generator/internal/astmodel/object_type.go
  v2/tools/generator/internal/astmodel/resource_type.go
Labels: technical-debt 📈

#3885 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr
