Repository Azure/azure-service-operator, pull requests merged in 2024-06, with the labels that each got.

#4052 Add Prom Rule groups and Azure Monitor accounts (workspaces)
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/alertsmanagement/_index.md
  docs/hugo/content/reference/monitor/_index.md
  v2/api/alertsmanagement/customizations/prometheus_rule_group_extension_types_gen.go
  v2/api/alertsmanagement/customizations/structure.txt
  v2/api/alertsmanagement/v1api20230301/doc.go
  v2/api/alertsmanagement/v1api20230301/groupversion_info_gen.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_spec_arm_types_gen.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_spec_arm_types_gen_test.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_status_arm_types_gen.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_status_arm_types_gen_test.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_types_gen.go
  v2/api/alertsmanagement/v1api20230301/prometheus_rule_group_types_gen_test.go
  v2/api/alertsmanagement/v1api20230301/storage/groupversion_info_gen.go
  v2/api/alertsmanagement/v1api20230301/storage/prometheus_rule_group_types_gen.go
  v2/api/alertsmanagement/v1api20230301/storage/prometheus_rule_group_types_gen_test.go
  v2/api/alertsmanagement/v1api20230301/storage/structure.txt
  v2/api/alertsmanagement/v1api20230301/storage/zz_generated.deepcopy.go
  v2/api/alertsmanagement/v1api20230301/structure.txt
  v2/api/alertsmanagement/v1api20230301/zz_generated.deepcopy.go
  v2/api/alertsmanagement/versions_matrix.md
  v2/api/monitor/customizations/account_extension_types_gen.go
  v2/api/monitor/customizations/structure.txt
  v2/api/monitor/v1api20230403/account_spec_arm_types_gen.go
  v2/api/monitor/v1api20230403/account_spec_arm_types_gen_test.go
  v2/api/monitor/v1api20230403/account_status_arm_types_gen.go
  v2/api/monitor/v1api20230403/account_status_arm_types_gen_test.go
  v2/api/monitor/v1api20230403/account_types_gen.go
  v2/api/monitor/v1api20230403/account_types_gen_test.go
  v2/api/monitor/v1api20230403/doc.go
  v2/api/monitor/v1api20230403/groupversion_info_gen.go
  v2/api/monitor/v1api20230403/storage/account_types_gen.go
  v2/api/monitor/v1api20230403/storage/account_types_gen_test.go
  v2/api/monitor/v1api20230403/storage/groupversion_info_gen.go
  v2/api/monitor/v1api20230403/storage/structure.txt
  v2/api/monitor/v1api20230403/storage/zz_generated.deepcopy.go
  v2/api/monitor/v1api20230403/structure.txt
  v2/api/monitor/v1api20230403/zz_generated.deepcopy.go
  v2/api/monitor/versions_matrix.md
  v2/azure-arm.yaml
  v2/internal/controllers/alertsmanagement_prometheusrulegroup_crud_v20230301_test.go
  v2/internal/controllers/controller_resources_gen.go
  v2/internal/controllers/monitor_account_crud_v20230403_test.go
  v2/internal/controllers/recordings/Test_AlertsManagement_PrometheusRuleGroup_CRUD.yaml
  v2/internal/controllers/recordings/Test_Monitor_Account_CRUD.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Alertsmanagement_v1api20230301_CreationAndDeletion.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Monitor_v1api20230403_CreationAndDeletion.yaml
  v2/samples/alertsmanagement/v1api20230301/refs/v1api20230403_monitor_account.yaml
  v2/samples/alertsmanagement/v1api20230301/v1api20230301_prometheusrulegroup.yaml
  v2/samples/monitor/v1api20230403/v1api20230403_account.yaml
  v2/tools/generator/internal/astmodel/package_import_set_test.go
Labels: new-resource

#4065 Fix breaking changes documentation ordering to be consistent
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.0.0-beta.4.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.0.0.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.1.0.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.2.0.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.4.0.md
  docs/hugo/content/guide/breaking-changes/breaking-changes-v2.6.0.md
Labels: documentation

#4056 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4068 [Automated] Add API Docs
  docs/hugo/content/reference/alertsmanagement/v1api20230301.md
  docs/hugo/content/reference/monitor/v1api20230403.md
Labels: automated pr

#4067 Add support for RoleDefinition resource
  Taskfile.yml
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/authorization/_index.md
  v2/api/authorization/customizations/role_definition_extension_types_gen.go
  v2/api/authorization/customizations/structure.txt
  v2/api/authorization/v1api20200801preview/role_assignment_defaults.go
  v2/api/authorization/v1api20220401/role_assignment_defaults.go
  v2/api/authorization/v1api20220401/role_definition_defaults.go
  v2/api/authorization/v1api20220401/role_definition_spec_arm_types_gen.go
  v2/api/authorization/v1api20220401/role_definition_spec_arm_types_gen_test.go
  v2/api/authorization/v1api20220401/role_definition_status_arm_types_gen.go
  v2/api/authorization/v1api20220401/role_definition_status_arm_types_gen_test.go
  v2/api/authorization/v1api20220401/role_definition_types_gen.go
  v2/api/authorization/v1api20220401/role_definition_types_gen_test.go
  v2/api/authorization/v1api20220401/storage/role_definition_types_gen.go
  v2/api/authorization/v1api20220401/storage/role_definition_types_gen_test.go
  v2/api/authorization/v1api20220401/storage/structure.txt
  v2/api/authorization/v1api20220401/storage/zz_generated.deepcopy.go
  v2/api/authorization/v1api20220401/structure.txt
  v2/api/authorization/v1api20220401/zz_generated.deepcopy.go
  v2/api/authorization/versions_matrix.md
  v2/api/documentdb/v1api20210515/sql_role_assignment_defaults.go
  v2/api/documentdb/v1api20231115/sql_role_assignment_defaults.go
  v2/azure-arm.yaml
  v2/internal/controllers/authorization_roledefinition_test.go
  v2/internal/controllers/controller_resources_gen.go
  v2/internal/controllers/crd_authorization_roleassignment_test.go
  v2/internal/controllers/recordings/Test_Authorization_RoleAssignment_OnResourceGroup_CRUD.yaml
  v2/internal/controllers/recordings/Test_Authorization_RoleAssignment_OnStorageAccount_CRUD.yaml
  v2/internal/controllers/recordings/Test_Authorization_RoleDefinitionResourceGroupScope_CRUD.yaml
  v2/internal/controllers/recordings/Test_Authorization_RoleDefinitionSubscriptionScope_CRUD.yaml
  v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Authorization_v1api20220401_CreationAndDeletion.yaml
  v2/internal/testcommon/samples_tester.go
  v2/internal/testcommon/samples_tester_test.go
  v2/internal/util/randextensions/uuid5.go
  v2/internal/util/randextensions/uuid5_test.go
  v2/samples/authorization/v1api20220401/v1api20220401_roledefinition.yaml
  v2/tools/generator/internal/astmodel/test_file_definition.go
Labels: new-resource

#4087 Redact password
  docs/v1/services/azuresql/azuresql.md
Labels: documentation

#4089 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4090 [Automated] Add API Docs
  docs/hugo/content/reference/_index.md
  docs/hugo/content/reference/authorization/v1api20220401.md
  docs/hugo/content/reference/containerservice/_index.md
  docs/hugo/content/reference/containerservice/v1api20231001.md
  docs/hugo/content/reference/containerservice/v1api20240402preview.md
  docs/hugo/content/reference/monitor/v1api20230403.md
Labels: automated pr

#4110 Improve secret rotation documentation, based on user pattern
  docs/hugo/content/guide/secrets.md
Labels: documentation

#4121 [Automated] Add API Docs
  docs/hugo/content/reference/containerservice/v1api20210501.md
  docs/hugo/content/reference/containerservice/v1api20230201.md
  docs/hugo/content/reference/containerservice/v1api20230202preview.md
  docs/hugo/content/reference/containerservice/v1api20231001.md
  docs/hugo/content/reference/containerservice/v1api20231102preview.md
  docs/hugo/content/reference/containerservice/v1api20240402preview.md
  docs/hugo/content/reference/network/v1api20220701.md
Labels: automated pr

#4120 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4132 [Automated] Add Helm Chart
  v2/charts/azure-service-operator-2.8.0.tgz
  v2/charts/azure-service-operator/Chart.yaml
  v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
  v2/charts/azure-service-operator/templates/v1_service_azureserviceoperator-controller-manager-metrics-service.yaml
  v2/charts/azure-service-operator/templates/v1_service_azureserviceoperator-webhook-service.yaml
  v2/charts/azure-service-operator/values.yaml
  v2/charts/index.yaml
Labels: automated pr
