Repository Azure/azure-service-operator, pull requests merged in 2024-05, with the labels that each got.

#3988 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4004 Fix broken documentation link
  docs/hugo/content/contributing/add-a-new-code-generated-resource.md
  v2/internal/testcommon/kube_per_test_context.go
Labels: documentation

#4006 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4007 [Automated] Add API Docs
  docs/hugo/content/reference/documentdb/v1api20231115.md
Labels: automated pr

#4015 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4045 Clarify documentation of code generator
  docs/hugo/content/tools/generator.md
Labels: documentation

#4034 [Automated] Update Code Structure Diagrams
  docs/hugo/content/contributing/aso-codegen-structure.svg
  docs/hugo/content/contributing/aso-v1-structure.svg
  docs/hugo/content/contributing/aso-v2-structure.svg
  docs/hugo/content/contributing/asoctl-structure.svg
Labels: automated pr

#4049 Use "never" rather than "" to mean "don't sync" for AZURE_SYNC_PERIOD.
  docs/hugo/content/guide/aso-controller-settings-options.md
  v2/charts/azure-service-operator/values.yaml
  v2/internal/config/vars.go
  v2/internal/config/vars_internal_test.go
  v2/pkg/common/config/config.go
Labels: breaking
